ДЗ 1
Froz1/2020-1-Atom-QA-Python-Z-Mamedov pull request #1
Opened 2020-03-05 13:23 UTC by Froz1

# Домашнее задание № 1

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:

* Создан репозиторий на Github

* Создано виртуальное окружение

* В папке tests созданы 5 файлов. В каждом по 5 тестов согласно требованиям в задании.

2020-03-12 14:12 UTC, sniiick requested changes
Есть пустые файлы, нужно удалить. Остальные комменты ниже

2020-03-12 14:12 UTC, snicks92 commented on .gitignore
> +*.pyc
Нужна пустая строка в конце файла

2020-03-12 14:12 UTC, snicks92 commented on pull_request_template.md
> +# Домашнее задание №1
Темплейт править не надо, на то он и темплейт. Гитхаб сам его подставляет в ПР

2020-03-12 14:12 UTC, snicks92 commented on Pipfile
> +[[source]]
Договаривались что пипфайл не кладем в проект. lock тоже

2020-03-12 14:12 UTC, snicks92 commented on Homework1/tests/test_5_int.py
> +        assert abs(-5) > 0
Почему бы сразу не проверить конкретное значение?

2020-03-12 14:12 UTC, snicks92 commented on Homework1/tests/test_5_int.py
> +    @pytest.mark.parametrize('i', list(range(5)))
Параметризация странная, между параметрами нет никакой разницы в рамках сравнения < 10

2020-03-14 10:58 UTC, Froz1 commented on pull_request_template.md
> +# Домашнее задание №1
Отредактировал файл, вернул к исходному состоянию.

2020-03-14 10:58 UTC, Froz1 commented on .gitignore
> +*.pyc
Добавлена пустая строка в конце файла.

2020-03-14 10:59 UTC, Froz1 commented on Pipfile
> +[[source]]
Удалил файлы Pipfile и Pipfile.lock

2020-03-14 11:00 UTC, Froz1 commented on Homework1/tests/test_5_int.py
> +        assert abs(-5) > 0
assert abs(-5) > 0 заменил на assert 5 // 2 == 2

2020-03-14 11:09 UTC, Froz1 commented on Homework1/tests/test_5_int.py
> +    @pytest.mark.parametrize('i', list(range(5)))
Изменил тест, добавил сравнение с 6.

2020-03-14 11:10 UTC, Froz1 commented
Замечания были исправлены, можно проверять.

2020-03-14 12:13 UTC, sniiick approved these changes
Ok

2020-03-14 12:13 UTC, merged