ДЗ 2
Froz1/2020-1-Atom-QA-Python-Z-Mamedov pull request #2
Opened 2020-04-05 17:51 UTC by Froz1

# Домашнее задание №

Прошу @snicks92, @sk1995 или @z1ll1 проверить его.

Что было сделано:
1) Написаны 5 тестов для UI;
2) Написаны 3 теста для API;
3) Реализована возможность запуска через selenoid;
4) Реализована возможность параллельного запуска тестов.

2020-04-12 13:10 UTC, snicks92 commented
Нужен ребейз на актуальный мастер и удаление ненужного коммита с 1 домашкой

2020-04-12 13:10 UTC, sniiick requested changes
Нужен ребейз на актуальный мастер и удаление ненужного коммита с 1 домашкой

2020-04-20 12:15 UTC, sniiick requested changes
Тесты не запускаются из за маски файлов (tests_

2020-05-12 11:11 UTC, snicks92 commented
ПР закрываю, так как с момента последних комментариев прошел почти месяц и уже идет итоговый проект

2020-05-12 11:11 UTC, closed without merging